### ISSUE TITLE
GUI Example: Focus intent + correlation intent shows empty viz

### ISSUE THREAD

**Issue by vsetlur** [tableau/vail#3]
There may be a possible bug in sort data.
Repro steps:
1. pick data: covid
2. click on "focus"; field: county, adjective: high
3. click on "correlation"

See video - 
https://user-images.githubusercontent.com/1739257/118053724-e3b91f00-b339-11eb-9576-4704c460744e.mov

**Comment by loki3** [comment]
This is the same basic problem as issue #4 - sortData issues a query that doesn't include all the fields needed by the viz, resulting in an empty viz. (There are other ways to fix the other bug, but fixing this one would also make that issue go away.)

**Comment by loki3** [comment]
Fixed the query problem so that all relevant fields are now in the result set, as well as being properly aggregated. The vizzes are no longer empty.

However, it now displays two identical vizzes due to issue #6
